server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://111.231.133.97:3306/sun?characterEncoding=utf8
    username: root
    password: Sife-558
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.sife.sun.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

